import type { Service, Theme } from '@/types';

export const mockThemes: Theme[] = [
  {
    id: 'theme-1',
    name: 'Clásico Negro',
    font_family: 'Inter',
    font_size: 48,
    font_color: '#FFFFFF',
    font_weight: '700',
    text_align: 'center',
    text_shadow: true,
    background_color: '#000000',
    background_image_url: null,
    padding: '40px',
    is_default: true,
  },
  {
    id: 'theme-2',
    name: 'Azul Worship',
    font_family: 'Inter',
    font_size: 52,
    font_color: '#FFFFFF',
    font_weight: '700',
    text_align: 'center',
    text_shadow: true,
    background_color: '#1e3a5f',
    background_image_url: null,
    padding: '40px',
    is_default: false,
  },
  {
    id: 'theme-3',
    name: 'Degradado Cálido',
    font_family: 'Georgia',
    font_size: 44,
    font_color: '#FFFFFF',
    font_weight: '600',
    text_align: 'center',
    text_shadow: true,
    background_color: '#4a1942',
    background_image_url: null,
    padding: '48px',
    is_default: false,
  },
];

export const mockService: Service = {
  id: 'service-1',
  organization_id: 'org-1',
  title: 'Servicio Dominical - 20 Julio 2025',
  date: '2025-07-20',
  status: 'draft',
  sections: [
    {
      id: 'section-1',
      service_id: 'service-1',
      title: 'Grande es tu Fidelidad',
      type: 'song',
      order_index: 0,
      slides: [
        {
          id: 'slide-1',
          section_id: 'section-1',
          order_index: 0,
          content: { lines: ['Grande es tu fidelidad', 'Oh Dios mi Padre'] },
          theme_id: 'theme-1',
          background_url: null,
          background_color: '#000000',
          notes: null,
        },
        {
          id: 'slide-2',
          section_id: 'section-1',
          order_index: 1,
          content: { lines: ['No hay sombra', 'de variación en Ti'] },
          theme_id: 'theme-1',
          background_url: null,
          background_color: '#000000',
          notes: null,
        },
        {
          id: 'slide-3',
          section_id: 'section-1',
          order_index: 2,
          content: { lines: ['Tu compasión', 'no tiene falla'] },
          theme_id: 'theme-1',
          background_url: null,
          background_color: '#000000',
          notes: null,
        },
      ],
    },
    {
      id: 'section-2',
      service_id: 'service-1',
      title: 'Salmo 23:1-6',
      type: 'scripture',
      order_index: 1,
      slides: [
        {
          id: 'slide-4',
          section_id: 'section-2',
          order_index: 0,
          content: { lines: ['Jehová es mi pastor;', 'nada me faltará.'] },
          theme_id: 'theme-2',
          background_url: null,
          background_color: '#1e3a5f',
          notes: 'Salmo 23:1',
        },
        {
          id: 'slide-5',
          section_id: 'section-2',
          order_index: 1,
          content: { lines: ['En lugares de delicados pastos', 'me hará descansar;'] },
          theme_id: 'theme-2',
          background_url: null,
          background_color: '#1e3a5f',
          notes: 'Salmo 23:2a',
        },
        {
          id: 'slide-6',
          section_id: 'section-2',
          order_index: 2,
          content: { lines: ['Junto a aguas de reposo', 'me pastoreará.'] },
          theme_id: 'theme-2',
          background_url: null,
          background_color: '#1e3a5f',
          notes: 'Salmo 23:2b',
        },
      ],
    },
    {
      id: 'section-3',
      service_id: 'service-1',
      title: 'Anuncios',
      type: 'announcement',
      order_index: 2,
      slides: [
        {
          id: 'slide-7',
          section_id: 'section-3',
          order_index: 0,
          content: { lines: ['Campamento Juvenil', '15-17 Agosto'] },
          theme_id: 'theme-3',
          background_url: null,
          background_color: '#4a1942',
          notes: null,
        },
        {
          id: 'slide-8',
          section_id: 'section-3',
          order_index: 1,
          content: { lines: ['Estudio Bíblico', 'Miércoles 7PM'] },
          theme_id: 'theme-3',
          background_url: null,
          background_color: '#4a1942',
          notes: null,
        },
      ],
    },
    {
      id: 'section-4',
      service_id: 'service-1',
      title: 'Cuán Grande es Él',
      type: 'song',
      order_index: 3,
      slides: [
        {
          id: 'slide-9',
          section_id: 'section-4',
          order_index: 0,
          content: { lines: ['Señor mi Dios', 'al contemplar los cielos'] },
          theme_id: 'theme-1',
          background_url: null,
          background_color: '#1a1a2e',
          notes: null,
        },
        {
          id: 'slide-10',
          section_id: 'section-4',
          order_index: 1,
          content: { lines: ['El firmamento y las estrellas mil'] },
          theme_id: 'theme-1',
          background_url: null,
          background_color: '#1a1a2e',
          notes: null,
        },
        {
          id: 'slide-11',
          section_id: 'section-4',
          order_index: 2,
          content: { lines: ['Mi corazón entona la canción', '¡Cuán grande es Él!'] },
          theme_id: 'theme-1',
          background_url: null,
          background_color: '#1a1a2e',
          notes: null,
        },
        {
          id: 'slide-12',
          section_id: 'section-4',
          order_index: 3,
          content: { lines: ['¡Cuán grande es Él!', '¡Cuán grande es Él!'] },
          theme_id: 'theme-1',
          background_url: null,
          background_color: '#1a1a2e',
          notes: null,
        },
      ],
    },
  ],
};
